### PR TITLE
Added inventory to new bags field in exporter json

### PR DESCRIPTION
**Pull request by namreeb**

### CODE REVIEW

**Comment by generalwrex** [comment]
Feel free to add your name in the author's area too for anyone that contribs, I'll test this when I get home to accept or comment on it

**Comment by namreeb** [comment]
Okay, I added myself :) Thanks!

**Comment by generalwrex** [comment]
I didn't inspect this PR yet.

**Comment by generalwrex** [comment]
I will move it back to my own repository if people don't let me inspect
anything to my own add-on.

**Comment by namreeb** [comment]
> I will move it back to my own repository if people don't let me inspect anything to my own add-on.
> […](#)

No rush as far as I’m concerned. Revert it and take your time.

**Comment by generalwrex** [comment]
Sorry for how I replied there, bad timing.

**Comment by jimmyt857** [comment]
I merged it because the size of the change is small and the code looked fine. @generalwrex sorry about that, I didn't realize you were still intending to do more testing.

**Pull request merged**
